In [1]:
%pip install requests python-dotenv

Requirement already satisfied: requests in c:\users\k7523\appdata\roaming\python\python312\site-packages (2.32.4)
Requirement already satisfied: python-dotenv in c:\python312\lib\site-packages (1.1.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\k7523\appdata\roaming\python\python312\site-packages (from requests) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\k7523\appdata\roaming\python\python312\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\python312\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\k7523\appdata\roaming\python\python312\site-packages (from requests) (2025.7.14)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd 
import requests
import os
import time
from dotenv import load_dotenv

In [3]:
load_dotenv()

API_KEY = os.getenv("API_KEY")

response = requests.get(f'https://api.themoviedb.org/3/movie/top_rated?api_key={API_KEY}&language=en-US&page=1')

In [4]:
df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [5]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,27.6608,8.713,29020
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,32.9409,8.686,21932
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,16.7545,8.572,13251
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,13.0188,8.567,16772
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,15.5842,8.549,9459

In [6]:
df = pd.DataFrame()

In [8]:
all_movies = [] 

for i in range(2, 429):
    url = f'https://api.themoviedb.org/3/movie/top_rated?api_key={API_KEY}&language=en-US&page={i}'
    
    try:
        response = requests.get(url, timeout=10)
        
        if response.status_code == 200:
            data = response.json()
            page_movies = data.get('results', [])
            if page_movies:
                all_movies.extend(page_movies)
                print(f"Successfully fetched page {i}")
            else:
                print(f"No results on page {i}. Stopping.")
                break
        else:
            print(f"Failed to fetch page {i}. Status code: {response.status_code}")
           
    except requests.exceptions.RequestException as e:
        print(f"An error occurred on page {i}: {e}")
    
    time.sleep(0.1) 

print("\nFinished fetching data. Creating DataFrame...")

df = pd.DataFrame(all_movies)
df.head()

Successfully fetched page 2
Successfully fetched page 3
Successfully fetched page 4
Successfully fetched page 5
Successfully fetched page 6
An error occurred on page 7: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 8: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 9
An error occurred on page 10: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 11: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 12
An error occurred on page 13: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 14
Successfully fetched page 15
An error occurred on page 16: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 17
An error occurred on page 18: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 19
Successfully fetched page 20
Successfully fetched page 21
Successfully fetched page 22
An error occurred on page 23: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 24: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 25
Successfully fetched page 26
An error occurred on page 27: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 28: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 29
Successfully fetched page 30
Successfully fetched page 31
An error occurred on page 32: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 33: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 34
Successfully fetched page 35
An error occurred on page 36: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 37
An error occurred on page 38: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 39
Successfully fetched page 40
Successfully fetched page 41
An error occurred on page 42: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 43
An error occurred on page 44: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 45
Successfully fetched page 46
Successfully fetched page 47
Successfully fetched page 48
Successfully fetched page 49
Successfully fetched page 50
An error occurred on page 51: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 52: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 53: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 54: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 55
Successfully fetched page 56
An error occurred on page 57: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 58: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 59
Successfully fetched page 60
Successfully fetched page 61
Successfully fetched page 62
Successfully fetched page 63
Successfully fetched page 64
Successfully fetched page 65
An error occurred on page 66: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 67: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 68
An error occurred on page 69: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 70: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 71
Successfully fetched page 72
Successfully fetched page 73
An error occurred on page 74: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 75
Successfully fetched page 76
Successfully fetched page 77
An error occurred on page 78: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 79: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 80
Successfully fetched page 81
Successfully fetched page 82
An error occurred on page 83: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 84: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 85: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 86: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 87
An error occurred on page 88: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 89
Successfully fetched page 90
Successfully fetched page 91
An error occurred on page 92: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 93
An error occurred on page 94: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 95: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 96
An error occurred on page 97: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 98: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 99: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 100
Successfully fetched page 101
An error occurred on page 102: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 103
An error occurred on page 104: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 105
Successfully fetched page 106
Successfully fetched page 107
Successfully fetched page 108
An error occurred on page 109: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 110
An error occurred on page 111: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 112: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 113: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 114
Successfully fetched page 115
An error occurred on page 116: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 117
An error occurred on page 118: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 119
Successfully fetched page 120
An error occurred on page 121: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 122: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 123: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 124
An error occurred on page 125: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 126
Successfully fetched page 127
An error occurred on page 128: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 129: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 130: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 131: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 132
Successfully fetched page 133
Successfully fetched page 134
An error occurred on page 135: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 136: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 137
An error occurred on page 138: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 139: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 140
Successfully fetched page 141
Successfully fetched page 142
An error occurred on page 143: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 144: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 145: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 146: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 147
Successfully fetched page 148
Successfully fetched page 149
An error occurred on page 150: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 151: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 152: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 153: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 154: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 155
An error occurred on page 156: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 157
Successfully fetched page 158
An error occurred on page 159: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 160
Successfully fetched page 161
Successfully fetched page 162
Successfully fetched page 163
An error occurred on page 164: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 165: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 166
An error occurred on page 167: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 168
Successfully fetched page 169
An error occurred on page 170: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 171
An error occurred on page 172: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 173
Successfully fetched page 174
An error occurred on page 175: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 176
Successfully fetched page 177
An error occurred on page 178: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 179
Successfully fetched page 180
An error occurred on page 181: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 182: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 183: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 184
An error occurred on page 185: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 186
An error occurred on page 187: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 188: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 189: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 190
Successfully fetched page 191
An error occurred on page 192: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 193
Successfully fetched page 194
An error occurred on page 195: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 196: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 197
Successfully fetched page 198
Successfully fetched page 199
An error occurred on page 200: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 201: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 202
Successfully fetched page 203
An error occurred on page 204: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 205
An error occurred on page 206: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 207: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 208
Successfully fetched page 209
An error occurred on page 210: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 211
An error occurred on page 212: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
An error occurred on page 213: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 214
Successfully fetched page 215
An error occurred on page 216: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Successfully fetched page 217

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/5TiwfWEaPSwD20uwXjCTUqpQX70.jpg,"[18, 53]",550,en,Fight Club,A ticking-time-bomb insomniac and a slippery s...,19.8808,/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg,1999-10-15,Fight Club,False,8.438,30877
1,False,/nC3IjYhUgZWgfKfFX0ygMigFwgc.jpg,"[28, 18, 36]",14537,ja,切腹,Down-on-his-luck veteran Tsugumo Hanshirō ente...,5.7556,/5konZnIbcAxZjP616Cz5o9bKEfW.jpg,1962-09-15,Harakiri,False,8.400,1120
2,False,/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg,"[18, 10749]",11216,it,Nuovo Cinema Paradiso,"A filmmaker recalls his childhood, when he fel...",6.1090,/gCI2AeMV4IHSewhJkzsur5MEp6R.jpg,1988-11-17,Cinema Paradiso,False,8.400,4625
3,False,/bxSBOAD8AuMHYMdW3jso9npAkgt.jpg,"[10751, 18]",667257,es,Cosas imposibles,"After the death of her abusive husband, Matild...",1.9188,/t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg,2021-06-17,Impossible Things,False,8.400,414
4,False,/uvitbjFU4JqvMwIkMWHp69bmUzG.jpg,"[18, 80]",598,pt,Cidade de Deus,In the poverty-stricken favelas of Rio de Jane...,8.6856,/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg,2002-08-30,City of God,False,8.430,7830

In [9]:
df = df[['id','title','overview','release_date','popularity','vote_average','vote_count']]
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,550,Fight Club,A ticking-time-bomb insomniac and a slippery s...,1999-10-15,19.8808,8.438,30877
1,14537,Harakiri,Down-on-his-luck veteran Tsugumo Hanshirō ente...,1962-09-15,5.7556,8.400,1120
2,11216,Cinema Paradiso,"A filmmaker recalls his childhood, when he fel...",1988-11-17,6.1090,8.400,4625
3,667257,Impossible Things,"After the death of her abusive husband, Matild...",2021-06-17,1.9188,8.400,414
4,598,City of God,In the poverty-stricken favelas of Rio de Jane...,2002-08-30,8.6856,8.430,7830

In [11]:
df.shape

(4700, 7)

In [12]:
df.to_csv('top_rated_movies.csv')